ManagementSystem/Models/City.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ManagementSystem.Models
{
    public class City : BaseModel
    {
        public string Name { get; set; }
        public int PostCode { get; set; }

        public int CountryID { get; set; }
        public virtual Country Country { get; set; }

        public virtual List<User> User { get; set; }

    }
}

ManagementSystem/Controllers/CitiesController.cs
using ManagementSystem.Models;
using ManagementSystem.Repositories;
using ManagementSystem.Services.ModelServices;
using ManagementSystem.ViewModels.CitiesVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagementSystem.Controllers
{
    public class CitiesController : BaseController
    {
        public ActionResult List()
        {
            CitiesListVM model = new CitiesListVM();
            TryUpdateModel(model);

            model.Cities = new CitiesService().GetAll();

            if (!string.IsNullOrEmpty(model.Search))
            {
                model.Cities = model.Cities.Where(c => c.Name.ToLower().Contains(model.Search) || c.PostCode.ToString().Contains(model.Search)).ToList();
            }

            switch (model.SortOrder)
            {
                case "name_asc": model.Cities = model.Cities.OrderBy(c => c.Name).ToList(); break;
                case "name_desc": model.Cities = model.Cities.OrderByDescending(c => c.Name).ToList(); break;
                case "postcode_asc": model.Cities = model.Cities.OrderBy(c => c.PostCode).ToList(); break;
                case "postcode_desc": model.Cities = model.Cities.OrderByDescending(c => c.PostCode).ToList(); break;
            }

            

            return View(model);
        }
        
        public ActionResult Edit(int? id)
        {
            CitiesEditVM model = new CitiesEditVM();
            CitiesService citiesService = new CitiesService();
            City city;

            if (id.HasValue)
            {
                city = citiesService.GetById(id.Value);
                if (city == null)
                {
                    return RedirectToAction("List");
                }
            }
            else
                city = new City();

            model.ID = city.ID;
            model.CountryID = city.CountryID;
            model.Name = city.Name;
            model.PostCode = city.PostCode;

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit()
        {
            CitiesEditVM model = new CitiesEditVM();
            CitiesService citiesService = new CitiesService();
            City city;

            TryUpdateModel(model);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.ID==0)
            {
                city = new City();
            }
            else
            {
                city = citiesService.GetById(model.ID);
                if (city == null)
                {
                    return RedirectToAction("List");
                }
            }

            city.ID = model.ID;
            city.CountryID = model.CountryID;
            city.Name = model.Name;
            city.PostCode = model.PostCode;

            citiesService.Save(city);

            return RedirectToAction("List");

        }

        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                new CitiesService().Delete(id.Value);
            }
            return RedirectToAction("List");
        }
    }
}

ManagementSystem/Views/Cities/Edit.cshtml
@model ManagementSystem.ViewModels.CitiesVM.CitiesEditVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>City</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PostCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PostCode, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CountryID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CountryID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CountryID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "List")
    </div>

ManagementSystem/Views/Cities/List.cshtml
@model ManagementSystem.ViewModels.CitiesVM.CitiesListVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

   
    <p>
        @Html.ActionLink("Create New", "Edit")
    </p>

@using (Html.BeginForm("List", "Cities", FormMethod.Get))
{
    <div>
        Search: @Html.TextBoxFor(model => model.Search, new { @class = "form-control" })
        <input type="submit" value="Search" class="btn btn-primary" />
    </div>
}
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Name", "List", "Cities", new RouteValueDictionary { { "SortOrder", Model.SortOrder == "name_asc" ? "name_desc" : "name_asc" }, { "Search", Model.Search } }, null)
            </th>
            <th>
                @Html.ActionLink("Post code", "List", "Cities", new RouteValueDictionary { { "SortOrder", Model.SortOrder == "postcode_asc" ? "postcode_desc" : "postcode_asc" }, { "Search", Model.Search } }, null)
            </th>            
            <th></th>
        </tr>
    
    @foreach (var item in Model.Cities) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PostCode)
            </td>           
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |                
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
    }
        @Scripts.Render("~/Scripts/jquery")
        @Scripts.Render("~/Scripts/bootstrap")
    </table>