ManagementSystem/Models/Country.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ManagementSystem.Models
{
    public class Country : BaseModel
    {
        public string Name { get; set; }
        public virtual List<City> Cities { get; set; }
    }
}

ManagementSystem/Controllers/CountriesController.cs
using ManagementSystem.Models;
using ManagementSystem.Repositories;
using ManagementSystem.Services.ModelServices;
using ManagementSystem.ViewModels.CountriesVM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagementSystem.Controllers
{
    public class CountriesController : BaseController
    {
        public ActionResult List()
        {
            CountriesListVM model = new CountriesListVM();
            TryUpdateModel(model);

            model.Countries = new CountriesService().GetAll();

            if (!string.IsNullOrEmpty(model.Search))
            {
                model.Countries = model.Countries.Where(c => c.Name.ToLower().Contains(model.Search)).ToList();
            }

            switch (model.SortOrder)
            {
                case "name_asc": model.Countries = model.Countries.OrderBy(c => c.Name).ToList(); break;
                case "name_desc": model.Countries = model.Countries.OrderByDescending(c => c.Name).ToList(); break;                
            }

            return View(model);
        }

        public ActionResult Edit(int? id)
        {
            CountriesEditVM model = new CountriesEditVM();
            CountriesService countriesService = new CountriesService();

            Country country;
            if (id.HasValue)
            {
                country = countriesService.GetById(id.Value);
                if (country==null)
                {
                    return RedirectToAction("List");
                }
            }
            else
             country = new Country();

            model.ID = country.ID;
            model.Name = country.Name;
            model.Cities = country.Cities;

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit()
        {
            CountriesEditVM model = new CountriesEditVM();
            CountriesService countriesService = new CountriesService();

            TryUpdateModel(model);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Country country;
            if (model.ID!=0)
            {
                country = countriesService.GetById(model.ID);
                if (country==null)
                {
                    return RedirectToAction("List");
                }
            }
            else
            {
                country = new Country();
            }

            country.ID = model.ID;
            country.Name = model.Name;
            country.Cities = model.Cities;

            countriesService.Save(country);

            return RedirectToAction("List");
        }

        public ActionResult Delete(int? id)
        {

            CountriesService countriesService = new CountriesService();
            if (id.HasValue)
            {
                countriesService.Delete(id.Value);                
            }

            return RedirectToAction("List");

        }
    }
}

ManagementSystem/Views/Countries/Edit.cshtml
@model ManagementSystem.ViewModels.CountriesVM.CountriesEditVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Country</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "List")
    </div>

ManagementSystem/Views/Countries/List.cshtml
@model ManagementSystem.ViewModels.CountriesVM.CountriesListVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <p>
        @Html.ActionLink("Create New", "Edit")
    </p>

@using (Html.BeginForm("List", "Countries", FormMethod.Get))
{
    <div>
        Search: @Html.TextBoxFor(model => model.Search, new { @class = "form-control" })
        <input type="submit" value="Search" class="btn btn-primary" />
    </div>
}
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Name", "List", "Countries", new RouteValueDictionary { { "SortOrder", Model.SortOrder == "name_asc" ? "name_desc" : "name_asc"},{ "Search", Model.Search } },null)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model.Countries) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |                
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
    }
    
    </table>